version: "3.7"

services:
  app:
    build: ./app
    ports:
      - "8999:8999"
    volumes:
      - .:/var/www/html
    networks:
      - jenkins

  jenkins-master:
    build:
      context: jenkins
      dockerfile: Dockerfile
    user: root
    ports:
      - "8181:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - "./jenkins/jenkins-data:/var/jenkins_home"
      - "./jenkins/jenkins-docker-certs:/certs/client:ro"
    restart: always
    depends_on:
      - jenkins-agent
    networks:
      - jenkins

  jenkins-agent:
    image: localhost:5000/devops_jenkins_agent
    build:
      context: jenkins
      dockerfile: Dockerfile_agent

  # ssh-keys:
  #   build:
  #     context: keygen
  #     dockerfile: Dockerfile
  #   volumes:
  #     - "./ssh-keys:/root/.ssh"

  # ansible:
  #   build:
  #     context: ansible
  #     dockerfile: Dockerfile
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - "./ansible/configs:/etc/ansible"
  #     - "./ssh-keys/id_rsa:/home/oladipo/.ssh/id_rsa"
  #   command: "chmod 700 /home/oladipo/.ssh && chmod 600 /home/oladipo/.ssh/id_rsa"
  #   networks:
  #     - ansible
  #   depends_on:
  #     - "ssh-keys"

  # server1:
  #   image: localhost:5000/server
  #   build:
  #     context: server
  #     dockerfile: Dockerfile
  #   privileged: true
  #   ports:
  #     - 22
  #   networks:
  #     - ansible
  #   volumes:
  #     - "./ssh-keys/id_rsa.pub:/home/oladipo/.ssh/authorized_keys"
  #   command: "chmod 700 /home/oladipo/.ssh && chmod 600 /home/oladipo/.ssh/authorized_keys"
  #   depends_on:
  #     - "ssh-keys"

  # server2:
  #   image: localhost:5000/server
  #   build:
  #     context: server
  #     dockerfile: Dockerfile
  #   privileged: true
  #   ports:
  #     - 22
  #   networks:
  #     - ansible
  #   volumes:
  #     - "./ssh-keys/id_rsa.pub:/home/oladipo/.ssh/authorized_keys"
  #   command: "chmod 700 /home/oladipo/.ssh && chmod 600 /home/oladipo/.ssh/authorized_keys"
  #   depends_on:
  #     - "ssh-keys"

  socat:
    image: alpine/socat
    networks:
      - jenkins
    ports:
      - "2376:2375"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  jenkins:
  # ansible:
